<?php
namespace Helper;

// here you can define custom actions
// all public methods declared in helper class will be available in $I

use Codeception\Module\Db;

class Acceptance extends \Codeception\Module
{
  public function _beforeSuite($settings = []) {
    parent::_beforeSuite($settings);
  }

  public function _afterSuite() {
    parent::_afterSuite(); // TODO: Change the autogenerated stub
  }
}
